//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristSpotsWebApplication.TouristSpotsServiceReferenceRem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TouristSpotsServiceReferenceRem.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTouristSpots", ReplyAction="http://tempuri.org/IService1/GetTouristSpotsResponse")]
        string GetTouristSpots(string latitude, string longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTouristSpots", ReplyAction="http://tempuri.org/IService1/GetTouristSpotsResponse")]
        System.Threading.Tasks.Task<string> GetTouristSpotsAsync(string latitude, string longitude);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TouristSpotsWebApplication.TouristSpotsServiceReferenceRem.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TouristSpotsWebApplication.TouristSpotsServiceReferenceRem.IService1>, TouristSpotsWebApplication.TouristSpotsServiceReferenceRem.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTouristSpots(string latitude, string longitude) {
            return base.Channel.GetTouristSpots(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<string> GetTouristSpotsAsync(string latitude, string longitude) {
            return base.Channel.GetTouristSpotsAsync(latitude, longitude);
        }
    }
}
